---
- hosts: frontend

  pre_tasks:
    - name: importing vars
      include_vars: vagrantConfig.yml

    - name: phantomjs dependencies
      apt: pkg={{ item }}
      sudo: true
      with_items:
        - git
        - libfontconfig1-dev 

    - name: config git email 
      shell: git config --global user.email {{ git.userEmail }}

    - name: config git name 
      shell: git config --global user.name {{ git.name }}

    - name: update npm
      sudo: true
      shell: npm install -g npm@next 

    - name: install gulp 
      sudo: true
      shell: npm install -g gulp 

    - name: install karma-cli
      sudo: true
      shell: npm install -g karma-cli
    
    - name: install bower
      sudo: true
      shell: npm install -g bower
    
    - name: clone secret keys if not already cloned
      git: repo=git@bitbucket.org:bastly/secret-keys.git dest=~/secret-keys accept_hostkey=True version=master
    
    - name: create .aws folder 
      command: mkdir ~/.aws

    - name: copy .npmrc to ~/
      command: cp ~/secret-keys/s3PublisherCredentials ~/.aws/credentials

    - name: install scss-lint 
      sudo: true
      shell: gem install scss-lint

    - name: install scss-lint 
      sudo: true
      shell: gem install sass


  roles: 
    - { role : bastly.git-publisher, repo_to_install: "git@bitbucket.org:bastly/frontendv1.git", app_installation_dir : "/vagrant/frontend"}
    - { role : bastly.git-publisher, repo_to_install: "git@bitbucket.org:bastly/user-panel.git", app_installation_dir : "/vagrant/user-panel"}

